FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

LABEL maintainer="IvanChet4 <wokewylf-111@mail.ru>"

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY ./script.sh /script.sh
RUN chmod +x /script.sh

COPY ./main.py /main.py

COPY ./app /app
WORKDIR /app/

ENV PYTHONPATH=/app

CMD ["/script.sh"]